"""Check A — change-prone complex files (hotspots.py)."""

from archagent.hotspots import find_hotspots, indent_complexity, is_excluded, looks_generated


def _write(root, rel, text):
    p = root / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text)


def _flat(lines=60):
    return "".join(f"line_{i} = {i}\n" for i in range(lines))


def _nested(lines=60, depth=4):
    pad = " " * (depth * 4)
    return "".join(f"{pad}line_{i} = {i}\n" for i in range(lines))


def test_indent_complexity_ignores_blank_lines():
    mean, n = indent_complexity("a = 1\n\n\n    b = 2\n")
    assert n == 2 and mean == 2.0


def test_indent_complexity_counts_a_tab_as_four():
    mean, n = indent_complexity("\tx\n")
    assert (mean, n) == (4.0, 1)


def test_excludes_vendored_generated_and_tests():
    assert is_excluded("src/vendor/lib.py")
    assert is_excluded("frontend/node_modules/x/y.js")
    assert is_excluded("app/migrations/0001_initial.py")
    assert is_excluded("static/js/jquery.min.js")
    assert is_excluded("tests/test_thing.py")
    assert is_excluded("src/app/thing.test.ts")
    assert not is_excluded("src/app/orders.py")


def test_generated_banner_is_recognized():
    assert looks_generated("# Code generated by protoc. DO NOT EDIT.\nx = 1\n")
    assert not looks_generated("x = 1\n# do not edit this line by hand\n" + "y\n" * 20)


def test_flags_only_files_high_on_both_axes(tmp_path):
    _write(tmp_path, "a.py", _nested())     # churny and complex  -> hotspot
    _write(tmp_path, "b.py", _flat())       # churny but flat
    _write(tmp_path, "c.py", _nested())     # complex but stable
    _write(tmp_path, "d.py", _flat())       # neither
    churn = {"a.py": 40, "b.py": 39, "c.py": 1, "d.py": 2}
    spots = find_hotspots(tmp_path, set(churn), churn)
    assert [h.path for h in spots] == ["a.py"]


def test_carries_fix_churn_and_percentiles(tmp_path):
    for name in ("a.py", "b.py", "c.py"):
        _write(tmp_path, name, _nested() if name == "a.py" else _flat())
    churn = {"a.py": 30, "b.py": 2, "c.py": 1}
    spot = find_hotspots(tmp_path, set(churn), churn, {"a.py": 12})[0]
    assert spot.fix_churn == 12
    assert spot.churn_pct == 1.0 and spot.complexity_pct == 1.0
    assert spot.score == 1.0


def test_small_and_unchanged_files_are_not_scored(tmp_path):
    _write(tmp_path, "tiny.py", _nested(lines=5))     # under MIN_LOC
    _write(tmp_path, "stale.py", _nested())           # no commits in the window
    _write(tmp_path, "big.py", _nested())
    churn = {"tiny.py": 50, "big.py": 50}
    spots = find_hotspots(tmp_path, {"tiny.py", "stale.py", "big.py"}, churn)
    assert [h.path for h in spots] == []  # big.py alone leaves nothing to compare against


def test_vendored_files_never_rank(tmp_path):
    _write(tmp_path, "src/vendor/huge.py", _nested(lines=400))
    _write(tmp_path, "src/app/a.py", _nested())
    _write(tmp_path, "src/app/b.py", _flat())
    _write(tmp_path, "src/app/c.py", _flat())
    churn = {"src/vendor/huge.py": 500, "src/app/a.py": 30, "src/app/b.py": 2, "src/app/c.py": 1}
    assert [h.path for h in find_hotspots(tmp_path, set(churn), churn)] == ["src/app/a.py"]
