"""`archagent --version` — small, and it exists for a specific failure.

`docs/RELEASING.md` step 7 verifies a release by running the CLI. That proves *a* build starts; it cannot
say which one, and the 0.3.0 smoke test had the same gap. It also showed up in calibration round 4, where
an artifact was generated by the working tree and reviewed against a July build, and nothing anywhere
recorded that two different archagents were involved (issue #13).
"""

from pathlib import Path

from typer.testing import CliRunner

from archagent.cli import app



# --- --version --------------------------------------------------------------------------------------

def test_version_prints_a_bare_parseable_version():
    """`RELEASING.md` step 7 verifies a release by running the CLI, which proves *a* build starts and
    cannot say which one. The first consumer of this flag is a script pinning what produced a scorecard,
    so the output is plain `print` — rich highlights a bare version as a number and emits colour codes.
    """
    import re

    from archagent import __version__
    result = CliRunner().invoke(app, ["--version"])
    assert result.exit_code == 0
    out = result.stdout.strip()
    assert out == __version__
    assert re.fullmatch(r"[0-9]+\.[0-9]+\.[0-9]+.*|0\+unknown", out), out
    assert "\x1b" not in result.stdout


def test_version_is_read_from_the_installed_distribution():
    """Hard-coding it in the package lets it drift from the wheel that is actually running, which is the
    one thing this flag exists to rule out."""
    from archagent import __version__
    assert "__version__" not in (Path(__file__).parents[1] / "pyproject.toml").read_text()
    assert __version__ and __version__ != "0+unknown"


def test_adding_the_callback_did_not_hide_the_commands():
    """A Typer callback changes how the group is built; the failure mode is a working `--version` and no
    subcommands."""
    out = CliRunner().invoke(app, ["--help"]).stdout
    for cmd in ("init", "gen", "check", "drift", "evaluate", "status"):
        assert cmd in out, cmd
