"""Which archagent produced this? (issue #13)

Every conclusion in an evaluation is relative to an archagent build. *"`drift` reports 0 items"* means
nothing without knowing which `drift`.

Calibration round 4 is the worked example. The artifact was generated by an agent invoking the working
tree; the human reviewer, following the brief, ran `archagent` from `PATH` — a build predating `v0.2.0`,
missing four of the commands the `describe` prompt tells agents to run. The reviewer correctly reported a
command as unavailable and reasonably concluded the artifact's note had drifted. It had not: **two
different archagents were used and nothing anywhere recorded that.**

The evaluation ledger pins the *target* revision religiously — `validate()` refuses a row without a
`target_commit`. It did not pin the tool. This is the other half.
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Tool:
    version: str                 # the installed distribution's version, or "0+unknown" from a source tree
    commit: str = ""             # short sha, when running from a checkout
    dirty: bool = False          # uncommitted changes in that checkout
    executable: str = ""         # what was actually invoked

    def stamp(self) -> str:
        """One line, for a review brief or an artifact log."""
        parts = [f"archagent {self.version}"]
        if self.commit:
            parts.append(f"commit {self.commit}{'+dirty' if self.dirty else ''}")
        return " · ".join(parts)

    @property
    def reproducible(self) -> str:
        """Why this build may not be reproducible, or "" if it looks pinned.

        A dirty tree is the case worth naming: the commit in the stamp is then a lower bound on what ran,
        and a later reader cannot recover the difference.
        """
        if self.version == "0+unknown":
            return "not installed as a distribution — running from a source tree"
        if self.dirty:
            return "uncommitted changes in the checkout; the commit below is not what ran"
        return ""


def _git(root: Path, *args: str) -> str:
    try:
        r = subprocess.run(["git", *args], cwd=root, capture_output=True, text=True, timeout=10)
        return r.stdout.strip() if r.returncode == 0 else ""
    except (OSError, subprocess.SubprocessError):
        return ""


def tool_info(root: Path | None = None) -> Tool:
    """The archagent that is running, as precisely as it can be determined."""
    try:
        from archagent import __version__ as version
    except Exception:                                     # noqa: BLE001 — never fail an evaluation on this
        version = "0+unknown"

    src = root or Path(__file__).resolve().parent.parent
    commit = _git(src, "rev-parse", "--short", "HEAD")
    dirty = bool(commit) and bool(_git(src, "status", "--porcelain"))

    import shutil
    return Tool(version=version, commit=commit, dirty=dirty,
                executable=shutil.which("archagent") or "")
