"""Check A — change-prone complex files: the files that change constantly *and* are hard to read.

A file that changes very often is not by itself a problem (a registry, a config table), and neither is a
long, deeply-nested one that nobody touches. The pair is the signal: an abstraction absorbing more and more
special cases churns *and* thickens. The construction — cross how often a file changes with how complex it
is — is Adam Tornhill's; the measurement choices here are ours.

Complexity is **indentation-based**: the mean leading-indent depth of non-blank lines, plus length. It needs
no per-language parser, which matters for a tool that scans Python, TypeScript, and whatever else a repo
mixes. It tracks nesting, which is what actually makes code hard to hold in your head. Validated against
Django and LiteLLM: the top-ranked files were the ORM query/compiler core, ModelAdmin, the LiteLLM router
and logging — exactly the files a maintainer would name (probe-results.md, experiment 4).

Both axes are converted to **percentiles within this repo** before being multiplied, so the check reads
"unusually churny and unusually complex *for this codebase*" rather than comparing against absolute numbers
that mean nothing across projects.
"""

from __future__ import annotations

import re
from bisect import bisect_left, bisect_right
from dataclasses import dataclass
from pathlib import Path

MIN_LOC = 30            # below this a file is too small for the complexity measure to mean anything
PCTILE_BAR = 0.75       # a file must sit in the top quartile on BOTH axes to be flagged
MAX_REPORTED = 10       # the ranked list is a starting point for a person, not an inventory
_TAB = 4                # a tab counts as this many columns

# Files whose churn and shape say nothing about *our* design. Without this the top of a real repo's list is
# jQuery internals and generated migrations (probe-results.md, experiment 2b).
_EXCLUDED_DIRS = {
    "node_modules", "vendor", "vendored", "third_party", "thirdparty", "external", "site-packages",
    "dist", "build", "generated", "__generated__", "migrations", "locale", "static", "assets",
    "fixtures", "snapshots", "__snapshots__", "tests", "test", "testing",
}
_EXCLUDED_NAME = re.compile(
    r"(\.min\.[a-z]+$|[._-]bundle\.|\bgenerated\b|_pb2\.py$|\.g\.[a-z]+$|"
    r"^test_|_test\.[a-z]+$|\.spec\.[a-z]+$|\.test\.[a-z]+$)",
    re.IGNORECASE,
)
# `DO NOT EDIT.` is only a banner when it ends the line — otherwise it catches ordinary prose warnings
# like "do not edit this by hand while the server is running".
_GENERATED_HEADER = re.compile(
    r"(auto-?generated|@generated|generated by|do not edit[.!]?\s*$)", re.IGNORECASE | re.MULTILINE)
_HEADER_LINES = 5       # a generated-file banner sits at the very top or not at all


@dataclass
class Hotspot:
    path: str
    churn: int           # commits touching the file in the window
    fix_churn: int       # of those, the ones the learned recognizer labels as fixes
    complexity: float    # mean indent depth
    loc: int
    churn_pct: float     # percentile within this repo, 0-1
    complexity_pct: float
    score: float         # churn_pct * complexity_pct


def is_excluded(rel: str) -> bool:
    """Vendored, generated, bundled, or test code — churn and nesting there aren't design signals."""
    parts = rel.split("/")
    if any(p.lower() in _EXCLUDED_DIRS for p in parts[:-1]):
        return True
    return bool(_EXCLUDED_NAME.search(parts[-1]))


def looks_generated(text: str) -> bool:
    """A `do not edit` / `@generated` banner in the first few lines."""
    head = "\n".join(text.splitlines()[:_HEADER_LINES])
    return bool(_GENERATED_HEADER.search(head))


def indent_complexity(text: str) -> tuple[float, int]:
    """`(mean leading-indent depth over non-blank lines, non-blank line count)`.

    Blank lines are skipped so a sparsely-formatted file isn't scored as flat. Nothing else is stripped:
    a comment sitting three levels deep is still evidence of three levels of nesting around it.
    """
    depths: list[int] = []
    for line in text.splitlines():
        if not line.strip():
            continue
        depth = 0
        for ch in line:
            if ch == " ":
                depth += 1
            elif ch == "\t":
                depth += _TAB
            else:
                break
        depths.append(depth)
    if not depths:
        return 0.0, 0
    return sum(depths) / len(depths), len(depths)


def _percentiles(values: dict[str, float]) -> dict[str, float]:
    """Each file's rank among the others, 0-1. Tied files share the average of the ranks they span, so a
    handful of equally-complex files all land high rather than all being pushed below the bar."""
    n = len(values)
    if n < 2:
        return {k: 1.0 for k in values}
    ordered = sorted(values.values())
    out: dict[str, float] = {}
    for k, v in values.items():
        lo, hi = bisect_left(ordered, v), bisect_right(ordered, v)
        out[k] = ((lo + hi - 1) / 2) / (n - 1)
    return out


def find_hotspots(
    root: Path,
    files: set[str],
    churn: dict[str, int],
    fix_churn: dict[str, int] | None = None,
    min_loc: int = MIN_LOC,
    bar: float = PCTILE_BAR,
) -> list[Hotspot]:
    """Files in the top `bar` percentile of *both* churn and complexity, most extreme first.

    `files` is the candidate set (already restricted to source); `churn` comes from the git miner. Files
    with no recorded change in the window are dropped rather than scored as zero-churn — they say nothing
    either way, and keeping them would distort everyone else's percentile.
    """
    fix_churn = fix_churn or {}
    complexity: dict[str, float] = {}
    loc: dict[str, int] = {}
    for rel in files:
        if is_excluded(rel) or churn.get(rel, 0) <= 0:
            continue
        try:
            text = (root / rel).read_text(errors="replace")
        except OSError:
            continue
        if looks_generated(text):
            continue
        mean_indent, n = indent_complexity(text)
        if n < min_loc:
            continue
        complexity[rel] = mean_indent
        loc[rel] = n

    if len(complexity) < 2:  # nothing to be "unusually" churny or complex relative to
        return []

    churn_pct = _percentiles({rel: float(churn[rel]) for rel in complexity})
    cx_pct = _percentiles(complexity)

    out: list[Hotspot] = []
    for rel in complexity:
        if churn_pct[rel] < bar or cx_pct[rel] < bar:
            continue
        out.append(Hotspot(
            path=rel, churn=churn[rel], fix_churn=fix_churn.get(rel, 0),
            complexity=round(complexity[rel], 2), loc=loc[rel],
            churn_pct=round(churn_pct[rel], 3), complexity_pct=round(cx_pct[rel], 3),
            score=round(churn_pct[rel] * cx_pct[rel], 3),
        ))
    out.sort(key=lambda h: (-h.score, -h.churn, h.path))
    return out
